# Generated by Django 4.1.4 on 2022-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('number', models.IntegerField(default=1)),
                ('resolution', models.CharField(choices=[('small', '256x256'), ('medium', '512x512'), ('large', '1024x1024')], max_length=8)),
            ],
        ),
    ]
